### ISSUE TITLE
run PacBio data without REF and FAST5

### ISSUE THREAD

**Issue by yangzuokun** [SouthGreenPlatform/CulebrONT#10]
Hi I'm trying to run  PacBio data, but no REF and FAST5 files, how to prepare these?

**Comment by francoissabot** [comment]
You do not need FAST5 (raw Nanopore data) or reference to run a simple assembly. Just do not activate Medaka (dedicated to Nanopore anyway) and comparison to reference.

**Comment by yangzuokun** [comment]
![image](https://user-images.githubusercontent.com/33180540/202824812-d01b3890-64b5-409e-8563-c1e5fe02ed52.png

**Comment by yangzuokun** [comment]
But how to define the REF and FAST5  in config.yaml ?

**Comment by sravel** [comment]
Hello, 
you can let emtpy string value like this
```
DATA:
    FASTQ: '/path/to/fastq/directory/'
    REF: ''
    GENOME_SIZE: '1m'
    FAST5: ''
    ILLUMINA: '/path/to/illumina/directory/'
    OUTPUT: '/path/to/output/directory/'
```
