### ISSUE TITLE
Cannot run circulator

### ISSUE THREAD

**Issue by mlpereira87** [SouthGreenPlatform/CulebrONT#13]
singularity exec /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/sitepackages/culebrONT/containers/Singularity.culebront_tools.sif circlator all

Traceback (most recent call last):
  File "/usr/local/miniconda/miniconda3/envs/mamba/envs/circlator/bin/circlator", line 57, in <module>
    exec('import circlator.tasks.' + task)
  File "<string>", line 1, in <module>
  File "/usr/local/miniconda/miniconda3/envs/mamba/envs/circlator/lib/python3.5/site-packages/circlator/__init__.py", line 26, in <module>
    from circlator import *
  File "/usr/local/miniconda/miniconda3/envs/mamba/envs/circlator/lib/python3.5/site-packages/circlator/bamfilter.py", line 2, in <module>
    import pysam
  File "/usr/local/miniconda/miniconda3/envs/mamba/envs/circlator/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.2: cannot open shared object file: No such file or directory

- Latest version of culebrONT

**Comment by sravel** [comment]
Hello can you replace your image to this image:

```
cd /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/sitepackages/culebrONT/containers
rm Singularity.culebront_tools.sif
singularity pull Singularity.culebront_tools.sif  oras://registry.forge.ird.fr/diade/culebront_pipeline/apptainer/apptainer.culebront_tools.sif:0.0.1
```

**Comment by mlpereira87** [comment]
Thank you for the reply. I was able to download the image and use it but I am facing another problem:

I could only run the pipeline test if I install the test folder in /tmp directory: `culebrONT test_install -d /tmp/`

If I install it in another directory, for example in my user home dir: `culebrONT test_install -d /home/aicampos/`

The pipeline cannot find the input fastq:

```
Error in rule run_flye:
    jobid: 7
    input: /home/aicampos/test_temp/Data-Xoo-sub/fastq/5PXoo1.fastq.gz
    output: /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/assembly.fasta, /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/assembly_info.txt, /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/FLYE-version.txt
    log: /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.o, /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.e (check log file(s) for error details)
    shell:
        
        [ ! -f /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/FLYE-version.txt ] &&  [ ! -d versions ] && mkdir -p versions; flye --version > /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/FLYE-version.txt
        ln -s -f /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/FLYE-version.txt /home/aicampos/test_temp/culebrONT_OUTPUT/versions/FLYE-version.txt
        (flye --nano-raw /home/aicampos/test_temp/Data-Xoo-sub/fastq/5PXoo1.fastq.gz  --genome-size 4.8m  --out-dir /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/ --threads 1;
        echo  /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER//assembly.fasta /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/assembly.fasta) 1>/home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.o 2>/home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.e
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.o: empty file
```

The error file /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/LOGS/5PXoo1_FLYE.e contains the following:

```
[2023-10-23 15:14:30] INFO: Starting Flye 2.9.2-b1786
[2023-10-23 15:14:30] ERROR: Can't open /home/aicampos/test_temp/Data-Xoo-sub/fastq/5PXoo1.fastq.gz
[2023-10-23 15:14:30] ERROR: Pipeline aborted
```

However the fastq file exist.
Also, if i run the Flye command with singularity but without using the culebrONT main command it works:

```
singularity exec /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/site-packages/culebrONT/containers/Singularity.culebront_tools.sif flye --nano-raw /home/aicampos/test_temp/Data-Xoo-sub/fastq/5PXoo1.fastq.gz  --genome-size 4.8m  --out-dir /home/aicampos/test_temp/culebrONT_OUTPUT/5PXoo1/ASSEMBLERS/FLYE/ASSEMBLER/ --threads 1
```


Output:

```
[2023-10-23 15:18:08] INFO: Starting Flye 2.9.2-b1786
[2023-10-23 15:18:08] INFO: >>>STAGE: configure
[2023-10-23 15:18:08] INFO: Configuring run
[2023-10-23 15:18:09] INFO: Total read length: 63698302
[2023-10-23 15:18:09] INFO: Input genome size: 4800000
[2023-10-23 15:18:09] INFO: Estimated coverage: 13
[2023-10-23 15:18:09] INFO: Reads N50/N90: 16019 / 4163
[2023-10-23 15:18:09] INFO: Minimum overlap set to 4000
[2023-10-23 15:18:09] INFO: >>>STAGE: assembly
[2023-10-23 15:18:09] INFO: Assembling disjointigs
[2023-10-23 15:18:09] INFO: Reading sequences
```
The same happen if I try to run CulebrONT with my data.

Maybe there is a problem with Snakemake not recognizing some directories...

**Comment by sravel** [comment]
How do you configure binding of singularity?
https://apptainer.org/docs/user/main/bind_paths_and_mounts.html
https://snakemake.readthedocs.io/en/stable/executing/cli.html#singularity
https://culebront-pipeline.readthedocs.io/en/latest/FAQ.html#frequently-asked-questions

please try with

```
culebrONT run_local -c /home/aicampos/test_temp/data_test_config.yaml --singularity-args "--bind /$HOME:/$HOME"
```

**Comment by mlpereira87** [comment]
Thank you for the reply! The pipeline can recognize my data now, but another problem was detected:

When I try to run with these configurations (1 nanopore fastq file and no illumina):

```
############ TOOLS ################
ASSEMBLY:
    CANU: false
    FLYE: true
    MINIASM: true
    RAVEN: true
    SMARTDENOVO:  true
    SHASTA: true

POLISHING:
    RACON: false

CIRCULAR: false

CORRECTION:
    NANOPOLISH: false
    MEDAKA: true
    PILON: false

FIXSTART: false

# BUSCO and QUAST will be launched on all activated steps (ASSEMBLY, POLISHING, CORRECTION)
QUALITY:
    BUSCO: true
    QUAST: true
#### Others quality tools are launched only in last assemblies
    BLOBTOOLS: true
    ASSEMBLYTICS: true
#### Others quality soft but illumina reads are required
    FLAGSTATS: false
    KAT: false
    MERQURY : false

#### Alignment of the various assemblies derived from a fastq file for small genomes (<10-20Mbp);
MSA:
    MAUVE: false

############ PARAMS ################
params:
    #### ASSEMBLY
    MINIMAP2:
        PRESET_OPTION: 'map-ont' # -x minimap2 preset option is map-pb by default (map-pb, map-ont etc)
    FLYE:
        MODE : '--nano-raw'
        OPTIONS: '' ## use --scaffold if flye>=2.9 # you can also use --resume option
    CANU:
        MODE : '-nanopore'
        OPTIONS: 'useGrid=false'
    SMARTDENOVO:
        KMER_SIZE: 16
        OPTIONS: '-J 5000'
    SHASTA:
        MEM_MODE: 'filesystem'
        MEM_BACKING: 'disk'
        OPTIONS: '--Reads.minReadLength 0 --config Nanopore-May2022'


    #### CIRCULAR
    CIRCLATOR:
        OPTIONS: ''


    #### POLISHING
    RACON:
        RACON_ROUNDS: 2                 #1 to 9


    #### CORRECTION
    CORRECTION_SEGMENTATION:
        SEGMENT_LEN: 50000              # segment length to split assembly and correct it  default=50000
        OVERLAP_LEN: 200                # overlap length between segments  default=200

    NANOPOLISH:
        OPTIONS: ''

    MEDAKA:
        SEGMENTATION: false              # if false, there is no segmentation of contigs for medaka
        MEDAKA_TRAIN_WITH_REF: false    # if 'MEDAKA_TRAIN_WITH_REF' is True, training uses reference to found in DATA REF param.

        # Medaka does not take in count other parameters below if MEDAKA_TRAIN_WITH_REF is TRUE.
        MEDAKA_MODEL_PATH: 'r104_e81_sup_g5015' # use a path if you have downloaded a model (or you want to use your own trained model) OR a simple string like 'r941_min_high_g303'
        MEDAKA_FEATURES_OPTIONS: '--batch_size 10 --chunk_len 100 --chunk_ovlp 10'
        MEDAKA_TRAIN_OPTIONS: '--batch_size 10 --epochs 500 '
        MEDAKA_CONSENSUS_OPTIONS: '--batch 200 '

    PILON:
        PILON_ROUNDS: 2                 #1 to 9
        OPTIONS: ''

    #### QUALITY
    BUSCO:
        #DATABASE: "DATA_DIR/Data-Xoo-sub/bacteria_odb10"
        DATABASE: 'bacteria_odb10 --update-data ' # use a path if you have downloaded a taxonomic database from busco OR a simple string like 'bacteria_odb10'
        MODEL: 'genome'
        SP: ''                         #--augustus-specie parameter on busco

    QUAST:
        GFF: ''
        OPTIONS: '--large'

    DIAMOND:
        DATABASE: '/data/BioISIGenomics_local/References/nr_DIAMOND/nr.dmnd'

    MUMMER:
        MINMATCH: 100                  # is -l option with default 20 on MUMMER
        MINCLUSTER: 500                 # is -c option with default 65 on MUMMER

    ASSEMBLYTICS:
        UNIQUE_ANCHOR_LEN: 10000
        MIN_VARIANT_SIZE: 50
        MAX_VARIANT_SIZE: 10000

    BLOBTOOLS:
        NAMES: '/data/BioISIGenomics_local/Azure_Devops/jupyter/users/aicampos/X2023/bacteria_empty/3Assembly/Taxon_nodes_names/names.dmp'
        NODES: '/data/BioISIGenomics_local/Azure_Devops/jupyter/users/aicampos/X2023/bacteria_empty/3Assembly/Taxon_nodes_names/nodes.dmp'

```

It could run several jobs except this:

```
Job 34: 
        Launching run_shasta
        threads: 256
        input:
            fastq: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/MISC/FASTQ2FASTA/barcode61.fasta
        output:
            fasta: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assemblyCIRCULARISEDTMPTAG.fasta
        params:
            ln -s /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/ShastaRun/Assembly.fasta /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assemblyCIRCULARISED.fasta 
            ln -s /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/ShastaRun/Assembly.gfa /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assembly_info.txt
        log:
            output: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/LOGS/barcode61_SHASTA.o
            error: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/LOGS/barcode61_SHASTA.e
        
Reason: Missing output files: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/SHASTA-version.txt, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assemblyCIRCULARISEDTMPTAG.fasta, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/BENCHMARK/ASSEMBLER/SHASTA.txt, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assembly_info.txt; Input files updated by another job: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/MISC/FASTQ2FASTA/barcode61.fasta


        [ ! -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/SHASTA-version.txt ] &&  [ ! -d versions ] && mkdir -p versions; shasta --version | head -n1 > /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/SHASTA-version.txt
        ln -s -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/SHASTA-version.txt /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/versions/SHASTA-version.txt
        (cd /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/;
        rm -rf ShastaRun/;
        shasta --command assemble --input /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/MISC/FASTQ2FASTA/barcode61.fasta --memoryMode filesystem --memoryBacking disk --threads 256 --Reads.minReadLength 0 --config Nanopore-May2022;
        ln -s /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/ShastaRun/Assembly.fasta /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assemblyCIRCULARISED.fasta ;
        ln -s /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/ShastaRun/Assembly.gfa /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/assembly_info.txt ) 1>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/LOGS/barcode61_SHASTA.o 2>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/ASSEMBLER/LOGS/barcode61_SHASTA.e
        
Activating singularity image /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/site-packages/culebrONT/containers/Singularity.culebront_tools.sif
Waiting at most 1296000 seconds for missing files.
```

It keeps waiting for the missing files and nothing happens.

Then I tried to deactivate Circulator:

´´´
CIRCULAR: false
´´´

This happened:

```
Job 87: 
        Launching run_blobtools ...
        threads: 1
        input:
            fasta: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/AGGREGATED_QC/DATA/barcode61-SHASTA-MEDAKA.fasta
            sorted_bam: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/MINIMAP2/minimap2mapping.bam
            diamond: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/DIAMOND/diamond.csv
        output:
            table: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/barcode61_SHASTA_MEDAKA.txt
        params:
            names: /data/BioISIGenomics_local/References/culebrONT/test/Data-Xoo-sub/blobtools/names.dmp
            nodes: /data/BioISIGenomics_local/References/culebrONT/test/Data-Xoo-sub/blobtools/nodes.dmp
        log:
            output: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/LOGS/barcode61_SHASTA_MEDAKA_BLOBTOOLS.o
            error: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/LOGS/barcode61_SHASTA_MEDAKA_BLOBTOOLS.e
        
Reason: Missing output files: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/barcode61_SHASTA_MEDAKA.txt; Input files updated by another job: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/AGGREGATED_QC/DATA/barcode61-SHASTA-MEDAKA.fasta, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/MINIMAP2/minimap2mapping.bam, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/DIAMOND/diamond.csv


        [ ! -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/BLOBTOOLS-version.txt ] &&  [ ! -d versions ] && mkdir -p versions; blobtools --version > /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/BLOBTOOLS-version.txt
        ln -s -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/BLOBTOOLS-version.txt /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/versions/BLOBTOOLS-version.txt
        (cd /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/ ;
        blobtools create -i /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/AGGREGATED_QC/DATA/barcode61-SHASTA-MEDAKA.fasta -b /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/MINIMAP2/minimap2mapping.bam -t /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/DIAMOND/diamond.csv -o quality --names /data/BioISIGenomics_local/References/culebrONT/test/Data-Xoo-sub/blobtools/names.dmp --nodes /data/BioISIGenomics_local/References/culebrONT/test/Data-Xoo-sub/blobtools/nodes.dmp --db nodesDB.txt;
        blobtools view -i quality.blobDB.json --cov -o output;
        blobtools plot -i quality.blobDB.json;
        mv quality.blobDB.*.blobplot.read_cov.bam0.png /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/read_cov.png;
        mv quality.blobDB.*.blobplot.bam0.png /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/blob.png) 1>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/LOGS/barcode61_SHASTA_MEDAKA_BLOBTOOLS.o 2>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/LOGS/barcode61_SHASTA_MEDAKA_BLOBTOOLS.e
        mv /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/output.quality.blobDB.table.txt /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/SHASTA/QUALITY/MEDAKA/BLOBTOOLS/barcode61_SHASTA_MEDAKA.txt
        
Activating singularity image /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/site-packages/culebrONT/containers/Singularity.culebront_tools.sif
Waiting at most 1296000 seconds for missing files.
```

Now it hangs on Blobtools but with a Shasta input... is there any problem with Shasta?

By last I decided to deactivate both Circulator and Shasta and this happened:

```

Job 44: 
        Launching run_assemblytics ...
        threads: 1
        input:
            delta: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/MUMMER/mummer.delta.gz
        output:
            summary: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/barcode61__FLYE__MEDAKA.Assemblytics_structural_variants.summary
        params:
            unique_anchor_length = 10000
            min_variant_size = 50
            max_variant_size = 10000
            prefix: barcode61__FLYE__MEDAKA
        log:
            output: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/LOGS/barcode61_FLYE_MEDAKA_ASSEMBLYTICS.o
            error: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/LOGS/barcode61_FLYE_MEDAKA_ASSEMBLYTICS.e
        
Reason: Missing output files: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/ASSEMBLYTICS-version.txt, /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/barcode61__FLYE__MEDAKA.Assemblytics_structural_variants.summary; Input files updated by another job: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/MUMMER/mummer.delta.gz


        [ ! -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/ASSEMBLYTICS-version.txt ] &&  [ ! -d versions ] && mkdir -p versions; whereis Assemblytics > /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/ASSEMBLYTICS-version.txt
        cp -f /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/ASSEMBLYTICS-version.txt /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/versions/ASSEMBLYTICS-version.txt
        (cd /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/;
        Assemblytics /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/MUMMER/mummer.delta.gz barcode61__FLYE__MEDAKA 10000 50 10000) 1>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/LOGS/barcode61_FLYE_MEDAKA_ASSEMBLYTICS.o 2>/home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/LOGS/barcode61_FLYE_MEDAKA_ASSEMBLYTICS.e
        
Activating singularity image /home/aicampos/miniconda3/envs/Culebront/lib/python3.10/site-packages/culebrONT/containers/Singularity.culebront_tools.sif
Waiting at most 1296000 seconds for missing files.

```

It is hanging again. I checked the stderr file: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/ASSEMBLYTICS/LOGS/barcode61_FLYE_MEDAKA_ASSEMBLYTICS.e

And it contains this:

```
Input delta file: /home/aicampos/X2023/validacoes_X/bacteria/validacoes_experimentais/barcode61_X/3Assembly/culebrONT_OUTPUT/barcode61/ASSEMBLERS/FLYE/QUALITY/MEDAKA/MUMMER/mummer.delta.gz
Output prefix: barcode61__FLYE__MEDAKA
Unique anchor length: 10000
Minimum variant size to call: 50
Maximum variant size to call: 10000
Logging progress updates in barcode61__FLYE__MEDAKA/progress.log
1. Filter delta file
2. Finding variants between alignments
Loaded 2 alignments
3. Finding variants within alignments
4. Combine variants between and within alignments
Warning message:
package 'ggplot2' was built under R version 4.2.3 
Warning message:
package 'plyr' was built under R version 4.2.3 
Warning message:
package 'RColorBrewer' was built under R version 4.2.3 
Error in revalue(bed$type, c(Repeat_expansion = "Repeat expansion", Repeat_contraction = "Repeat contraction",  : 
  x is not a factor or a character vector.
Execution halted
Warning message:
package 'ggplot2' was built under R version 4.2.3 
Warning messages:
1: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
i Please use `linewidth` instead. 
2: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
i Please use the `linewidth` argument instead. 
Warning message:
package 'ggplot2' was built under R version 4.2.3 
Warning message:
package 'scales' was built under R version 4.2.3 
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
i Please use `linewidth` instead. 
/usr/local/mamba/mamba/envs/assemblytics/bin/Assemblytics: line 120: zip: command not found
/usr/local/mamba/mamba/envs/assemblytics/bin/Assemblytics: line 123: column: command not found

```
