### ISSUE TITLE
culebrONT test run giving error!

### ISSUE THREAD

**Issue by aswathyseb** [SouthGreenPlatform/CulebrONT#6]
Hi,

Thank you for this pipeline. I am testing out using the test dataset on a local machine.

The command I ran is

`culebrONT run_local -t 8 -c test/data_test_config.yaml`

But I get this error 

`Error in rule run_canu:
    jobid: 7
ERROR:  Invalid command line option '/home/aswathy/tmp/test/Data-Xoo-sub/fastq/5percentB1-1.fastq.gz'.  Did you forget quotes around options with spaces?
`

Attached is the detailed error message.  

[error.txt](https://github.com/SouthGreenPlatform/culebrONT/files/8224565/error.txt)

Could you please help me resolve this?

Thank you

**Comment by sravel** [comment]
Hello Thanks for use CulebrONT !!!
Could you please send us complet log file? we need to ckeck the snakemake command line to help you

However, we think you need to binding singularity: see https://sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html

you have 2 solutions to bind singularity:

* directly on the culebront command line `culebrONT run_local -t 8 -c test/data_test_config.yaml --singularity-args "--bind $HOME"`
* or declaring a singularity global variable in your system, doing a `export SINGULARITY_BIND="/home:/home"` in your  ~/.bashrc 

We wait for your news !

Thanks,

**Comment by aswathyseb** [comment]
Binding singularity solved the issue. I was able to run it.

Thank you.

**Comment by aswathyseb** [comment]
Hello, 

Unfortunately when I try on my dataset I get the error that my fastq file doen't exist when it is actually present in the folder.  The command I ran is 

`time culebrONT run_local -c config.yaml -t 15 --singularity-args "--bind $HOME"`

Attached are the log files and the config file

[snakemake.log](https://github.com/SouthGreenPlatform/culebrONT/files/8238091/snakemake.log)

[config.yaml.txt](https://github.com/SouthGreenPlatform/culebrONT/files/8238097/config.yaml.txt)

[ccs_MINIASM.e.txt](https://github.com/SouthGreenPlatform/culebrONT/files/8238098/ccs_MINIASM.e.txt)

Could you please help?

**Comment by sravel** [comment]
Hello
Can you write the snakemake command line in the log file?
Is it the good path?
`/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/data/fastq/ccs.fq`

because when you write relative path on config.yaml the absolute path is build relative to the file:
so for you i think is like this:

```bash
/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/config.yaml
/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/data/fastq
/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/data/refs/PlasmoDB-52_Pyoeliiyoelii17X_Genome.fasta
/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/culebrONT_OUTPUT
```

cant you try to write absolute path on your config.yaml like:
```yaml
DATA:
    FASTQ: '/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/data/fastq/'
    FAST5: ''
    ILLUMINA: ''
    GENOME_SIZE: '23m'
    REF: '/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/data/refs/PlasmoDB-52_Pyoeliiyoelii17X_Genome.fasta'
    OUTPUT: '/analysis/work/aswathy/projects/scott-linder/pacbio_assembly_pyoelii/trials/culebrONT/culebrONT_OUTPUT/'
```
